apiVersion: v1
kind: Pod
metadata:
  name: get-started-pod
  labels:
    app: web
spec:
  containers:
    - name: web-app
      image: docker/getting-started
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: get-started-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31111
    protocol: TCP
  selector:
    app: web