apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
  labels:
   app : configmap
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - name: configmap
    image: berktoprakci/app:3.0
    imagePullPolicy: IfNotPresent # Use Always for security if Registry is trusted.
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 9000
    volumeMounts:
      - name: app-config-vol
        mountPath: /etc/config
    env:
    - name: USERNAME # Must match with environment variable name in the app.
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: username
          # optional: true
          # if its unnecessary
    - name: PASSWORD
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: password
    - name: USERADMIN
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: user.admin
    # Use envFrom to define all of ConfigMap's data as container environment variables.
    # The key from the ConfigMap becomes the environment variable name in the Pod. ie: username.log.level
    # You can declare the environment variable name by using "env" as above.
    envFrom:
    - configMapRef:
        name: app-config
  volumes:
  - name: app-config-vol
    configMap:
      name: app-config

---

apiVersion: v1
kind: Service
metadata:
  name: configmap-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9000
  selector:
    app: configmap