apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
  labels:
   app : configmap
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - name: configmap
    image: berktoprakci/app:3.0
    imagePullPolicy: IfNotPresent # Use Always for security if Registry is trusted.
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 9000
    volumeMounts:
      - name: secrets-vol
        mountPath: /etc/config
    env:
    - name: USERNAME # Must match with environment variable name in the app.
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: username
          # optional: true
          # if its unnecessary
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: password
    - name: USERADMIN
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: user.admin
    # Use envFrom to define all of Secret's data as container environment variables.
    # The key from the Secret becomes the environment variable name in the Pod. ie: username.log.level
    # You can declare the secret variable name by using "env" as above.
    envFrom:
    - secretRef:
        name: app-secrets
  volumes:
  - name: secrets-vol
    secret:
      secretName: app-secrets

---

apiVersion: v1
kind: Service
metadata:
  name: configmap-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9000
  selector:
    app: configmap