apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscale-deploy
  labels:
    app: deploy-nginx
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi" #128 MB
            cpu: "200m" #200 millicpu (1000m = 1 CPU)
          requests:
            memory: 100Mi
            cpu: 150m

---

apiVersion: v1
kind: Service
metadata:
  name: autoscale-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31100
    protocol: TCP
  selector:
    app: my-nginx