apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: autoscale-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: autoscale-deploy
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 90