apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc # registered with DNS
spec:
  type: NodePort
  ports:
  - port: 80 # ClusterIp port
    targetPort: 8080 # Container port
    nodePort: 31122 # Node port
    protocol: TCP
  selector:
    app: web