apiVersion: v1
kind: Pod
metadata:
  name: hello-nginx
  labels:
    app: nginx
spec:
  containers:
    - name: my-nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 15
        timeoutSeconds: 2 
        periodSeconds: 5 
        failureThreshold: 1 
      readinessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 5 
        failureThreshold: 1 
        successThreshold: 3
      startupProbe:
        httpGet:
          path: /index.html
          port: 80
        failureThreshold: 30 
        periodSeconds: 10 